<?php

/**
 * @file
 * Fonctions principales pour le module Custom Dashboard.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function custom_dashboard_theme($existing, $type, $theme, $path) {
  return [
    'dashboard' => [
      'variables' => [
        'header' => [],
        'rows' => [],
        'purge_cache_link' => '',
        'seo_check_link' => '',
      ],
      'template' => 'dashboard',
      'path' => $path . '/templates',
    ],
  ];
}
